version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.10

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Generate coverage report
          command: npm run coverage

  codeclimate:
    docker:
      - image: codeclimate/codeclimate
    environment:
      CC_TEST_REPORTER_ID: 1fd33f8f1aad76daa08264a9deb799daa253fdca5fbbe1eb8de85901e653cbf8
    steps:
      - checkout
      - run:
          name: Prepare CodeClimate
          command: |
            apk update && apk add curl curl-dev bash
            curl -L https://github.com/codeclimate/test-reporter/releases/download/v0.8.0/codeclimate-test-reporter-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run CodeClimate
          command: |
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?

workflows:
  version: 2
  build_and_test:
     jobs:
      - build:
          filters:
            branches:
              only:
                  - main
      - codeclimate:
          requires:
            - build