version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:16.10
      
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  
  frontend-tests:
    <<: *defaults
    steps:
      - checkout 
      - attach_workspace:
          at: ~/repo/tmp
      - run: npm install
      - run: 
          name: Run frontend tests
          command: |
            npm test
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths: 
            - codeclimate.frontend.json
  
  upload-coverage:
    <<: *defaults
    environment: 
      CC_TEST_REPORTER_ID: 1fd33f8f1aad76daa08264a9deb799daa253fdca5fbbe1eb8de85901e653cbf8
    docker:
      - image: codeclimate/codeclimate
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2

  commit:
    jobs:
      - build
      - frontend-tests: 
          requires: 
             - build
      - upload-coverage:
          requires:
             - frontend-tests